### ISSUE TITLE
MultiAddress parsing

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#194]
https://github.com/status-im/nim-beacon-chain/pull/1081 removes some multiaddress parsing code that obviously doesn't belong there - it would be nice to have this in libp2p proper - ie ways to extract interesting parts from a multiaddr

**Comment by Menduist** [comment]
The proc linked is to transform a MultiAddress to a ENode, and since ENode is a nim-eth type, it doesn't belongs in nim-libp2p
The multiaddress has been improved over the years, and will continue to do so, so writing this proc is becoming more and more painless (ie, it could use `initTAddress(MultiAddress)`)
