### ISSUE TITLE
Should not warn on unknown protocol

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#206]
```
WRN 2020-06-07 17:53:06+02:00 no handlers for                            tid=592327 file=multistream.nim:148 protocol=/meshsub/1.1.0 topic=Multistream
```

that other peers support other protocols is "normal" - dbg suitable most likely

**Comment by sinkingsugar** [comment]
In a local branch I actually shuffled lot of those messages around, not super satisfied yet but maybe a broader issue and discussion should be opened to improve the logging. 
Not sure how much of  a priority it is tho.

**Comment by dryajov** [comment]
I'm fine with `DBG` for this one. Also, a lot of our current messages should be `DBG` (in fact, originally they were), but they are `TRACE` because of the default level for debug builds, which otherwise polutes CI and make parsing out test output hard, visually. 

In short, we should shuffle a lot of this, but as we've found already, more often than not it gets in the way, so we keep coming back to `TRACE`.
