### ISSUE TITLE
More memory and perf profiling

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#207]
libp2p needs better memory and performance profiles that can expose possible regressions and potential issues, such as memory leaks and performance degradation. It would be beneficial to be able to run this as part of CI, or at least as a dedicated job that can highlight and expose potential issues as well as help identify and troubleshoot them.

**Comment by sinkingsugar** [comment]
I agree but don't you think that this is a global nim issue? 
I definitely think so personally.
So I'm not sure exactly how we can make it scoped just to libp2p.

**Comment by dryajov** [comment]
Well, this is a discussion issue, so the idea is to figure out the best approach, I don't know what it looks like yet. We might have to hook the GC for this, but whatever it ends up being, it needs to allows us to detect and resolve this type of issues quickly.  So, ideas on how to do this better are welcome and this is what the issue is about. 

> So I'm not sure exactly how we can make it scoped just to libp2p.

It isn't, but before we go hooking the gc, we need to figure out how to best instrument our code with things like metrics. I don't see this two as conflicting, they should complement each other.

**Comment by stefantalpalaru** [comment]
This should help, by showing the GC's allocated and used memory in the main thread: https://github.com/status-im/nim-metrics/pull/39

**Comment by Menduist** [comment]
This issue is a bit outdated, IMO

We now have better tools to track memory usages in applications (nim-metrics improved, the [heaptrack branch](https://github.com/status-im/Nim/tree/heaptrack_support), etc)

Our testbed for memory is currently the nimbus test fleet, which is not ideal because it's "external", but it's certainly good enough for now.
Doing memory bench-marking during CI seems tricky

Please re-open if needed
