### ISSUE TITLE
`publish` broken

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#242]
As mentioned before, the likely culprit for many issues is gossipsub publish - it is indeed broken in several ways:

Unconditionally, it enters `rebalanceMesh` which may take long time:

https://github.com/status-im/nim-libp2p/blob/7a95f1844b039a3f9fc1d9dc6b9fe7182aafba39/libp2p/protocols/pubsub/gossipsub.nim#L467

`rebalanceMesh` uses `sleepAsync` in a loop - this indicates faulty logic as sleeping ones way out of synchronization issues leads to nondeterministic behaviour:

https://github.com/status-im/nim-libp2p/blob/7a95f1844b039a3f9fc1d9dc6b9fe7182aafba39/libp2p/protocols/pubsub/gossipsub.nim#L106

it's also weird - this code for example is a strange noop:

https://github.com/status-im/nim-libp2p/blob/7a95f1844b039a3f9fc1d9dc6b9fe7182aafba39/libp2p/protocols/pubsub/gossipsub.nim#L115

and since it's an async method using `await`, it might "block" publishing the message for a long time - even if, for example, there is more than 1 peer already available for the topic, because it keeps looping.

**Comment by sinkingsugar** [comment]
I agree, I already started refactoring in gossip 1.1 branch, removed repeats and sleep

It should be acceptable to publish with 0 peers immediately after switch start....
Some tests were failing.. yes but they just needed the `waitSub` utility

**Comment by sinkingsugar** [comment]
One issue I noticed is also that go with coroutines model makes it easy to just locate bottlenecks and defer them.. as a result they have mostly sync and easy to debug code...
While in our case we have a miriad of async/await...

**Comment by sinkingsugar** [comment]
Also... `publish` maybe should just return the number of peers it published to.. if we want to have users to realize it was a "empty" publish.. just an idea

**Comment by arnetheduck** [comment]
> started refactoring

ok, so that will need backporting - we need this working asap in 1.0

**Comment by sinkingsugar** [comment]
Fine for me.. 
This is the dilemma tho:
> It should be acceptable to publish with 0 peers immediately after switch start....

Can we confirm that this statement is ok? If not we might need to return a counter of deliveries or so

**Comment by dryajov** [comment]
> Unconditionally, it enters rebalanceMesh which may take long time:

Where are we supposed to publish if there are no peers?

> rebalanceMesh uses sleepAsync in a loop - this indicates faulty logic as sleeping ones way out of synchronization issues leads to nondeterministic behaviour:

The sleep, as it states, is to prevent starving the event loop. If you look at the code, you'll see that there aren't any `await`'s, which means that there is no concurrency in that block and in effect it will lock up the event loop until the condition of the loop is satisfied. The sleep is intentional and it makes sense there because peers are constantly moving in and out of the different tables because they are being provided by external (ambient) discovery, if we don't allow the event loop some time to process, we're not going to get any peers and it will spin forever.

> and since it's an async method using await, it might "block" publishing the message for a long time - even if, for example, there is more than 1 peer already available for the topic, because it keeps looping.

We can rework this to publish early if peers are available and trigger the rebalance logic after messages where sent (as a fire and forget task). 

But the question is what to do if no peers are available, do we fail early?

**Comment by sinkingsugar** [comment]
I think this can be closed @dryajov , correct?

**Comment by dryajov** [comment]
yes, this has been ameliorated significantly.
