### ISSUE TITLE
Prevent Mplex-induced deadlocks

### ISSUE THREAD

**Issue by zah** [status-im/nim-libp2p#337]
Consider the following order of events:

1) Incoming request for a new sub-protocol stream is received from a peer P.
2) The mplex read loop invokes a handler for the protocol. 
   The handler is started with `asyncCheck`, but further writes are awaited with `channel.pushTo`.
3) As part of the logic of the handler, new dials are performed and awaited (this blocks the read loop on the `pushTo` call)
4) The peer P sends us more data, opens new streams, etc. After filling a buffer, these are also blocked on the `channel.pushTo` op of the multiplexer.
5) Some of the blocked sends from step 4 may interfere with the dials started in step 2
6) The dials never complete and the read loop is never resumed resulting in a deadlock preventing all further communication with peer P.

**Comment by dryajov** [comment]
>  2. The mplex read loop invokes a handler for the protocol.
> The handler is started with asyncCheck, but further writes are awaited with channel.pushTo.

This is done for backpressure, `pushTo` blocks because we need to stop accepting data once some limit is reached.

> 3. As part of the logic of the handler, new dials are performed and awaited (this blocks the read loop on the pushTo call)

> 4. The peer P sends us more data, opens new streams, etc. After filling a buffer, these are also blocked on the channel.pushTo op of the multiplexer.

After taking a look at the current implementation of `dial`, locks are released by the time the dial from within `pubsubpeer` is being called. Right now, this only happens on a connection event, here https://github.com/status-im/nim-libp2p/blob/master/libp2p/switch.nim#L362 and the lock is released here, https://github.com/status-im/nim-libp2p/blob/master/libp2p/switch.nim#L351. We need to trace that flow again, because it seems unlikely that it will lock up the way that is being described. All other invocations of `dial` should happen outside of the dial flow. For reference, the `dial` called from within the `PubSubPeer` send aren't locked and are simply pulling an existing connection from the connection manager here https://github.com/status-im/nim-libp2p/blob/master/libp2p/switch.nim#L386-L393.

**Comment by arnetheduck** [comment]
>  For reference, the dial called from within the PubSubPeer send aren't locked and are simply pulling an existing connection from the connection manager here https://github.com/status-im/nim-libp2p/blob/master/libp2p/switch.nim#L386-L393.

the `dial` in PubSubPeer is locked by the lock in `PubSubPeer` - it doesn't grab a connection from the connection manager - it opens a new channel with mplex (effectively) - the channel negotiation needs  `mplex` to work / be reading data

**Comment by arnetheduck** [comment]
fixed in #342
