### ISSUE TITLE
Asynclock was already released.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-libp2p#454]
One of my nodes got crashed because of such thing:
```
{"lvl":"DBG","ts":"2020-11-24 20:26:06.865+00:00","msg":"Exception in poll()","topics":"beacnde","tid":480833,"file":"nimbus_beacon_node.nim:797","exc":"AsyncLockError","err":"AsyncLock was already released!","node":"brewery-1"}
```
There no more consumers of `AsyncLock` primitive in `nim-beacon-chain` except `switch.nim`.

**Comment by arnetheduck** [comment]
If I were to venture a guess, it's those loops and exceptions inside of the try/finally

**Comment by dryajov** [comment]
Agree, does sound like the try/catch bug - shouldn't happen on it's own. Is this on Linux or Windows @cheatfate?

**Comment by cheatfate** [comment]
Its Linux, but i think it is also possible on Windows.

**Comment by sinkingsugar** [comment]
Well there is only a single asynclock... and it's indeed inside a try/finally, released on finally.
I don't see how it should escape, unless it's a "finally" bug.

**Comment by arnetheduck** [comment]
it's an exception bug - loops and exceptions don't mix in async, have to split this up into multiple proc's and try/catches

**Comment by dryajov** [comment]
As I was refactoring this, I realized that we're checking for the `locked` flag on the AsyncLock here https://github.com/status-im/nim-libp2p/blob/master/libp2p/switch.nim#L324, which suggest that there is something else going on in the lock itself, because otherwise we should have not hit this branch even with the broken tray/finally.
