### ISSUE TITLE
Unhandled exception: value out of range [RangeDefect] under Nim 1.4 

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#483]
```
/Users/dryajov/.choosenim/toolchains/nim-1.4.0/lib/pure/unittest.nim(646) testvarint
/Users/dryajov/.choosenim/toolchains/nim-1.4.0/lib/system/fatal.nim(49) sysFatal

    Unhandled exception: value out of range [RangeDefect]
  [FAILED] vsizeof() edge cases test
/Users/dryajov/personal/projects/status/nim-libp2p/tests/testvarint.nim(233) testvarint
/Users/dryajov/.choosenim/toolchains/nim-1.4.0/lib/system/fatal.nim(49) sysFatal

    Unhandled exception: value out of range [RangeDefect]
  [FAILED] [ProtoBuf] Success edge cases test
```

**Comment by dryajov** [comment]
@cheatfate could you please take a look at this?

**Comment by dryajov** [comment]
This is also broken in the latest `version-1-2` branch and at least since v1.2.8.

**Comment by cheatfate** [comment]
I think this is Nim compiler's regression because actually all the values of `uint64` range is valid sequences for `int64` range, so value which is bigger than `0x7FFF_FFFF_FFFF_FFFF'u64` should be converted to negative integer. I really want to avoid `cast[T]` because it makes it impossible to use `varint` at compile time. But looks like we are forced to replace all conversions with casts.

**Comment by tersec** [comment]
https://github.com/nim-lang/Nim/issues/15210
