### ISSUE TITLE
Incoming connections take up all the connection slots on Eth2 mainnet

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#595]
Through the behaviour is observed on Eth2 mainnet, I'm logging the issue here as this is a problem that can manifest in other production environments.

There is discrepancy with outgoing (dialed by us) vs incoming (us being dialed) connections. On mainnet all 160 slots are usually taken up by incoming connections, this is due to many things, like firewalls, but it's also potentially due to the TCP backlog. 

I suspect that having a TCP backlog of 100 allows incoming connections to always "get in" before outgoing and since the connection semaphore is shared across both, it eventually ends up using all the slots. 

One thing to try out is to set the backlog to something much lower, like twice as many in flight upgrades (4 currently). We need to be careful as it's always better to have more incoming connections vs no connections at all, but not being able to dial peers will hamper connecting to specific peers located through discovery - for example, it will be impossible to connect to nodes on specific pubsub topics unless this is fixed.

**Comment by Menduist** [comment]
I'm afraid it probably won't be as simple

### A bit of background on TCP backlog
(talking about linux here, and I'm ignoring the syn backlog for simplicity)
The backlog is simply a queue of **established** connection that the program will `accept` in a few moments. The "established" part is important, because as soon as a connection is in the backlog, the client **is connected**.
This system has been design to, for instance, buffer for a bit during the time a HTTP server computes something, but is really not made for a server where you don't mind to loose a few incoming connections.

But what happens if the backlog is full? Well, the server will simply ignore the connection request, and the TCP client will think that the packet got lost for some reason, and retry the connection will an exponential backoff, as any connection attempt.

Some issues arise with high ping client, but in the scope of the libp2p, we could probably have a backlog of `1` and everything would still work as expected

#### Note on docker
The docker networking is happily ignoring whatever backlog we set inside the container. So, while inside the container, we do have a backlog of 100:
```bash
ss -ln | grep LISTEN
tcp   LISTEN 0      100          0.0.0.0:9100        0.0.0.0:*
```
(btw, `0` is the backlog size, and `100` the backlog capacity, useful to diagnose this kind of things)

On the host, docker use a backlog of 4096:
```bash
ss -ln | grep LISTEN
tcp   LISTEN 0      4096         0.0.0.0:9100        0.0.0.0:*
```
So, in our current infra, the host will accept the connection even if we have a low backlog


### How do we solve this then
I think the issue is coming from the fact that we acquire the [semaphore _before_ accepting](https://github.com/status-im/nim-libp2p/blob/72ccd1d1f55764df35087b063ed38f688f517d6a/libp2p/connmanager.nim#L449) the connection.
Currently, at the instant that a connection closes, and thus the semaphore as a free slot, the `accept loop` will take this slot, and block on `accept` afterward. (Looking at a few servers, we generally have 0 clients in the backlog, so accept _will_ block the semaphore)

The other current issue is that if the semaphore is full, the clients connecting will pile up in the backlog, not knowing that we aren't handling them.

Unfortunately, I don't see a silver bullet here. The best options in my mind is to accept a client, try to get a semaphore slot afterward, and if we fail to get a slot in a timely manner, kick the peer.
On the application side, we need to make sure that when we kick a few peers to dial new, better scored ones, we make enough room for a few incoming peers.
That _should_ stop the starving of outgoing connections.


But I think my current peer cycling mechanism in nimbus would actually work right now, since I kick 2 peers everytime, the accept loop will take one slot, but during the upgrade of the incoming connection I have time to dial a new peer before the accept loop takes the other slot

**Comment by dryajov** [comment]
> Unfortunately, I don't see a silver bullet here. The best options in my mind is to accept a client, try to get a semaphore slot afterward, and if we fail to get a slot in a timely manner, kick the peer.

This is an issue with many concurrent causes, like network topology (Nat, backlog, etc...), so I agree there is hardly a silver bullet for this.

We can't accept connections and drop them because for some transports (websocket for example) there will be costly handshakes before it even gets to libp2p - we want to avoid this. Accept and the semaphore are in place precisely so that we have better control over when and how connections make it to libp2p - if we can't process the connection we should not be attempting to pick it up. 

On  the other hand, I believe that (and this is what I'd like to confirm), queued up connections have a better chance of making it to libp2p - this is mostly a hunch, not something that I'm certain about :)

We do have a workaround for this, the semaphore is split into incoming and outgoing and we can control the split however we want, it just happens that right now both default to the same semaphore object - https://github.com/status-im/nim-libp2p/blob/master/libp2p/connmanager.nim#L90-L96

**Comment by Menduist** [comment]
Well, if we think about it in a more "basic" way, currently, accepting is greedy (since we take a semaphore slot before actually accepting, and accepting could block for minutes), and dialing is lazy (since we take the semaphore slot just before dialing)

So, to fix this, we need to either make dialing greedy, or accepting lazy

Since we have currently no control over the dialing, making the dialing greedy would be the program job, not ours, so we can't reliably choose that

Hence the choice to make accepting a lazy operation. If we don't want to accept all the time, we could add a "lazy get" to the semaphore, which is just waiting for an empty slot without taking it, and only call `accept` when we actually have an empty slot.


Other implementations of the libp2p do not have a hard cap on connection count, and will instead kick peers when a threshold is reached. I like our solution better, since it avoid a saw-tooth pattern, and having to continuously kick peers even if they are good peers. But indeed, our approach does mean that we have to deal with incoming peers when we have no room for them (where other implem would accept them an potentially kick them at the next cycle)

**Comment by Menduist** [comment]
More infos: On `u-libp2p-u`, we have about ~3 incoming peers per minute, so if we have < 3 disconnects per minutes, incoming will take all the slots. I'll check tomorrow the number of disconnects (not as trivial to check unfortunately)

**Comment by arnetheduck** [comment]
The other potential way forward is to simply not cap outgoing connections, just count them against the incoming semaphore. That would be coupled with a pause on outgoing connections once the mesh for all interesting topics is full.

**Comment by dryajov** [comment]
We have the split connection count for precisely this reason, we can just set outgoing connections to something high, like 100/60 and guarantee that outgoing connections have enough room to never get capped.

**Comment by arnetheduck** [comment]
> We have the split connection count for precisely this reason, we can just set outgoing connections to something high, like 100/60 and guarantee that outgoing connections have enough room to never get capped.

that's different: you get 160 total connections then - what I'm suggesting is that outgoing connections can always be made, but the semaphore holds a total - if there are "too many" (semaphore is negative), incoming connections stop.

**Comment by dryajov** [comment]
> The other potential way forward is to simply not cap outgoing connections, just count them against the incoming semaphore. That would be coupled with a pause on outgoing connections once the mesh for all interesting topics is full.

> that's different: you get 160 total connections then - what I'm suggesting is that outgoing connections can always be made, but the semaphore holds a total - if there are "too many" (semaphore is negative), incoming connections stop.

This essentially makes the idea of connection counts advisory, i.e. non enforceable. I get what your saying and it might be a way of doing it, but I don't see any advantage over just having a more deterministic split?

**Comment by arnetheduck** [comment]
>  advantage over just having a more deterministic split?

because when we need connections because the mesh is bad and find them in discovery on the right subnet, nothing should get in the way of connecting to those peers - it's more important to have a healthy mesh - when we don't need any more connections, we simply.. stop making outgoing connections - the absolutely most important function of the connection limit is to ensure we don't get spammed by incomings.

**Comment by dryajov** [comment]
> the absolutely most important function of the connection limit is to ensure we don't get spammed by incomings.

There are two semaphores and incoming connections aren't counted against outgoing, which means that you can dial out as many times as you want until you reach an upper limit for `outgoing` connections. With a large enough count for outgoing (or incoming), it essentially becomes a build in a failsafe for potential regressions that would trigger way to many dials. For example, if you set the `outgoing` counts to something like `1000` and `incoming` to `100`, under normal conditions you wouldn't hit that upper `1000` connections limit.

**Comment by arnetheduck** [comment]
yeah, so to put it in perspective, until now, the "rule" implemented for outgoing connections was "no more than X" - but with subnet walking we ask a better question - "do we need more connections to have a good mesh" - ie instead of a limiting number, the decision is based on our mesh needs at the moment. 

On top of that, we want to "allow" a certain number of incoming connections _unless_ we've already hit an upper limit on _total_ connections. With separate semaphores, outgoing connections _don't_ count against the incoming semaphore - this means that in your example, we will have 1000 outgoing connections _and_ 60 incoming connections whereas in the logic I'm proposing, we'll have 1000 because as soon as there are 60 connenctions of any kind, the incoming connection tap it closed.

**Comment by Menduist** [comment]
The semaphore question is more related to connection management than this issue.

Imo, this issue is "with a naive connection management (eg just a max connection count), incoming and outgoing connection should have equal chances", and I'm currently testing out a lazy accept on a nimbus node to try to achieve this

On the conn management side, it's an ongoing discussion, but I think most people would want to be able to put a hard limit on connection count. Having too many connection could cause performance issue, or even [issues with your ISP](https://discuss.ipfs.io/t/banned-by-internet-provider-for-running-private-ipfs-gateway/6754) or with [your router](https://github.com/ipfs/go-ipfs/issues/3320)

To achieve this hard limit properly, the current plan is basically, for instance in the case of nimbus, to kick bad peers when we don't have a good mesh to make room for better peers.
But we could imagine having a different strategy for people with "unlimited resources", and indeed have a dynamic cap on the connection count for each direction.

**Comment by Menduist** [comment]
This has been fixed thanks to peer cycling, peer trimming and forced outgoing connections
