### ISSUE TITLE
`Connection.readLP` exception unsafe

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#64]
`LPStreamIncompleteError` or `LPStreamReadError` will cause 
https://github.com/status-im/nim-libp2p/blob/d42833947a4baddf21da8ac3105e2d5956a6daac/libp2p/connection.nim#L121 to return a seq of length 10 initialized here: https://github.com/status-im/nim-libp2p/blob/d42833947a4baddf21da8ac3105e2d5956a6daac/libp2p/connection.nim#L118

https://github.com/status-im/nim-libp2p/blob/d42833947a4baddf21da8ac3105e2d5956a6daac/libp2p/connection.nim#L130 will return a partially initialized seq instead

if `readExactly` leaks some other exception (as it will, now or in the future when the code changes without this code being updated), it will pass through, leaving `s` in a broken and inconsistent state having read an unknown number of bytes - given that exceptions rarely are handled correctly, this will cause further issues when `s` is reused incorrectly, swallowing the root cause that was hidden here.

**Comment by dryajov** [comment]
I don't follow the logic. Yes, `result` would end up being partially initialized, but it would not leak because a) there aren't any references to it outside of the proc if/when an exception is thrown, ie. no dangling refs and it should be properly GCd on the next cycle and b) the whole point of throwing exceptions is to break the normal flow of the execution and allow exception/error handling code to kick in, furthermore, it's impossible to capture the return value of a proc that raised an exception, so there is no way of consuming the partially captured result. 

This could be an issue if `readLp` took a ref/pointer to an external variable that was created outside of the scope of the proc and that pattern could be more dangerous with exceptions (`readExactly ` could actually exhibit this behaviour in other contexts), but `readLp` should be safe for all intents and purposes, unless the language exception mechanism and GC is broken beyond repair, which I don't think is the case with Nim?

I think fundamentally, all your arguments around `exceptions` being the wrong choice have come from the perspective of `return` values (it has been the central theme of this discussions, so allow me to bring it in here as well), which is an apples to oranges comparison. We can't argument exception handling from the perspective of return values, they are fundamentally different mechanisms and have different trade offs.

> if readExactly leaks some other exception (as it will, now or in the future when the code changes without this code being updated), it will pass through, leaving s in a broken and inconsistent state having read an unknown number of bytes

This is one example of that apples to oranges argumentation. Yes, `s` would be in an inconsistent state, that is by design and exceptions assume that the `world` is in an inconsistent state when they are raised, that is why exceptions terminate the process if they are unhandled. Of course the developer could handle the exception and try to recover from it, and it might or might not be the right thing to do, depending on the situation, but fundamentally that is by design. In contrast, with a return value, one can simply "forget" to handle it and continue down the execution path as if nothing had happened without any indication of something being off. Which one is more dangerous?

**Comment by cheatfate** [comment]
@dryajov if exception happens inside
```nim
for i in 0..<len(result):
      await s.readExactly(addr result[i], 1)
      res = LP.getUVarint(result.toOpenArray(0, i), length, size)
      if res == VarintStatus.Success:
        break
```
it will be catched by one of your exception handlers:
```nim
  except LPStreamIncompleteError as exc:
    trace "remote connection ended unexpectedly", exc = exc.msg
  except LPStreamReadError as exc:
    trace "couldn't read from stream", exc = exc.msg
```
this exception handlers will echo traced exception and clean current exception. So sequence of 10 bytes will be returned as successful result, and this sequence can have from 0 to 9 bytes filled.

**Comment by dryajov** [comment]
Ugh, thanks @cheatfate , you are correct - here is a fix #67 .

**Comment by arnetheduck** [comment]
> so allow me to bring it in here as well

lol, sometimes an apple is an apple: https://github.com/status-im/nim-libp2p/pull/32/files#r328467365

the GC will help you reclaim memory sometimes - it unfortunately won't save you from held locks, open files and other resources being leaked, state being inconsistent/partially written/corrupted etc. 

Nim lacks basic exception safety tools like RAII so if you want to find bugs, code that uses exceptions in nim tends to be broken on the exception path (ie anywhere on the call stack where the exception passes through).

**Comment by zah** [comment]
Well, it's not true that Nim lacks RAII features. I've been too busy after the upgrade to 1.0 to review the current state of destructors, but they might already be good enough for us to start using them. Even without destructors, Nim has `finally` and `defer` which is already more than Java for example.

**Comment by arnetheduck** [comment]
finally: https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html
defer(ish): https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by arnetheduck** [comment]
also, practically, `defer` and `finally` require the developer to remember to type them out and the compiler does not help with this, thus it generally doesn't happen (and isn't raii)..

**Comment by zah** [comment]
Nim has Java's `try` with templates like `withFile` or `lock`. So it's fair to count an extra score point for `defer` :) And let's not forget that destructors are just around the corner, or perhaps already good enough to use.

**Comment by arnetheduck** [comment]
mitigated in #67
